### ISSUE TITLE
review the saps-arrebol recovery process

### ISSUE THREAD

**Issue by thiagoyeds** [fogbow/saps-engine#68]
It seems we are missing at least one part: the recovery when the saps was not able to receive the jobID from arrebol (in this case, saps will try to recover based on job label). So, we can take this opportunity to review the plan against the code (also, remember to properly doc the plan).

**Comment by wesleymonte** [comment]
It dependes on issue [#73](https://github.com/ufcg-lsd/arrebol/issues/73) from Arrebol. It is already being developed

**Comment by thiagomanel** [comment]
Hi @wesleymonte and @thiagoyeds. Maybe, I have made a poor description of this issue. It does not depend on issue #73

What we want to do is to check arrebol is following the fault tolerance design. If not, we should provide a list of what it is made wrong and what is missed.

@thiagoyeds did we have any description of the expected behaviour? I remember we discussed about this a few times but I'm not sure we wrote it down.

**Comment by wesleymonte** [comment]
Hi @thiagomanel, I think you confused the issues. The #73 I'm talking about is in the Arrebol project. A part of the tasks recovery flow depends on the capture of jobs by the label in Arrebol.

**Comment by thiagomanel** [comment]
No. What I meant was this issue, 68, should not depend on any issue, ok?

**Comment by thiagoyeds** [comment]
Move to https://github.com/ufcg-lsd/saps-scheduler/issues/10
